name: Main

on:
  pull_request:
    branches:
      - 'develop'
  push:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        env:
          COVERAGE: true
          RAILS_ENV: test
          CI: true
          COVERALLS_REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: docker-compose --file docker-compose.ci.yml run ci
